version: "3.8"

services:

  db:
    image: ghcr.io/illarion-ev/illarion-dev-postgres
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - type: volume
        source: local-db
        target: /var/lib/postgresql/data
      - type: volume
        source: pg-socket
        target: /var/run/postgresql
    environment:
      POSTGRES_USER: illarion
      POSTGRES_PASSWORD: illarion
      POSTGRES_DB: illarion
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U illarion"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    restart: always
    image: dpage/pgadmin4:7
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./db-servers.json
        target: /pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: user@illarion.local
      PGADMIN_DEFAULT_PASSWORD: illarion
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    logging:
      driver: none

volumes:
  local-db:
  pg-socket:
