version: "3.8"

services:

  db:
    image: ghcr.io/illarion-ev/illarion-dev-postgres
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - type: volume
        source: local-db
        target: /var/lib/postgresql/data
      - type: volume
        source: pg-socket
        target: /var/run/postgresql
    environment:
      POSTGRES_USER: illarion
      POSTGRES_PASSWORD: illarion
      POSTGRES_DB: illarion
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U illarion"]
      interval: 10s
      timeout: 5s
      retries: 10

  phppgadmin:
    restart: always
    image: bitnami/phppgadmin:7.13.0
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
    logging:
      driver: none

volumes:
  local-db:
  pg-socket:
