version: "3.8"

services:

  db:
    image: ghcr.io/illarion-ev/illarion-dev-postgres
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - type: volume
        source: local-db
        target: /var/lib/postgresql/data
      - type: volume
        source: pg-socket
        target: /var/run/postgresql
    environment:
      POSTGRES_USER: illarion
      POSTGRES_PASSWORD: illarion
      POSTGRES_DB: illarion
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U illarion"]
      interval: 10s
      timeout: 5s
      retries: 10

  phppgadmin:
    restart: always
    image: dockage/phppgadmin:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=Local Illarion
      - PHP_PG_ADMIN_SERVER_HOST=db
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=illarion

volumes:
  local-db:
  pg-socket:
