version: "3.8"

services:

  game-server:
    entrypoint: /usr/local/share/docker-init.sh
    command: bash -c "cd /server/build && cmake .. && make && /server/build/src/illarion /server/setup/illarion.conf || sleep infinity"
    build:
      context: modules/Server/.devcontainer
      args:
        VARIANT: bullseye
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "13000:3012"
    volumes:
      - type: bind
        source: ./modules/Content
        target: /scripts
        read_only: true
      - type: bind
        source: ./modules/Map
        target: /maps
        read_only: true
      - type: bind
        source: ./modules/Server
        target: /server
      - type: bind
        source: ./modules/Server/build
        target: /server/build
      - type: volume
        source: saved-maps
        target: /usr/share/illarion/map
      - type: volume
        source: pg-socket
        target: /var/run/postgresql

volumes:
  saved-maps:
